spring:
  application:
    name: friendexam
    
  datasource:
    url: jdbc:mysql://localhost:3306/exampledb
    username: ${username}
    password: ${password}
    driver-class-name: com.mysql.cj.jdbc.Driver
