spring:
  application:
    name: springmvc

# message property 설정
  messages:
    basename: messages
    encoding: utf-8
    cache-duration: 0

# 기존 whitelabel page 제거
server:
  error:
    whitelabel:
      enabled: false
